### ISSUE TITLE
DeepSeq tool broken on GHC 7.10

### ISSUE THREAD

**Issue by adamgundry** [iconnect/api-tools#43]
The generated instances of `DeepSeq` for enumerations rely on the default method, which changed in 7.10 to use `Generic`, causing compilation failures due to missing `Generic` instances if the tool is used. Perhaps we should generate `Generic` instances anyway (cf. #32)?

**Comment by adinapoli** [comment]
:+1: On my side to get those extra tools if it makes our lives easier. At the end of the day they are quite useful instances!
