### ISSUE TITLE
Support copy-pasting schema changelog validation errors

### ISSUE THREAD

**Issue by adamgundry** [iconnect/api-tools#6]
In simple cases, the pretty-printed schema changelog validation error messages are in exactly the right format to copy-paste back into the changelog, which is very convenient. However, some manual editing may be required. Some simple changes could reduce the need for this:
  * include `default ...` clause where required
  * sort missing types and components in reverse dependency order
  * include `|` symbols when printing new unions/enums

**Comment by adamgundry** [comment]
Yet another case: when using a keyword (like `version`) as a record field name, quotes are required by the parser (`'version'`), but not printed.

**Comment by cdornan** [comment]
Yes of course.

**Comment by adamgundry** [comment]
Following #46 the only cases I'm aware of in which the changelog cannot be copy pasted are things that require manual intervention anyway: missing default values, and incompatible definitions of schema types.

**Comment by cdornan** [comment]
@adamgundry shall we close this?

**Comment by adamgundry** [comment]
Perhaps we should. :smile:
